### ISSUE TITLE
Resolver don’t use evaluate_policy method

### ISSUE THREAD

**Issue by Malian** [trailblazer/trailblazer#102]
Hello !

I see in Trailblazer::Operation::Resolver that the build_operation don't instanciate the policy with the evaluate_policy method. I have override the evaluate_policy method for adding some parameters but I can't use the resolver now.

Do you have a solution ?

Thanks a lot !

**Comment by apotonick** [comment]
This is fixed in TRB2, you can plug the policy whereever you need it: http://trailblazer.to/gems/operation/2.0/policy.html#pundit
