### ISSUE TITLE
Validations processed twice

### ISSUE THREAD

**Issue by johnlane** [trailblazer/trailblazer#109]
I'm flagging this issue before I forget it.

I recently upgraded my Trailblazer stack to the latest (TRB 1.1.0) after a short period away. After doing so, some of my tests failed and I discovered this was due to dupliated error messages coming from validations.

I found that any validation that I specified in the property definition using the below syntax was being executed twice:

```
property :title, validates: {presence: { message: t('.select', name: t('.title'))    } }
```

If I replaced such examples like the below, everything worked fine again:

```
property :title
validates :title, presence: { message: t('.select', name: t('.title'))    }
```

The error manifests as duplicated error messages in `errors[:title]` 

Expected:

```
:title=>[\"Please select your title\"]
```

Actual

```
:title=>[\"Please select your title\", \"Please select your title\"]
```

(Prior to upgrade my Trailblazer Gem was `apotonick/trailblazer#d7f18498` which did not exhibit this behaviour.)

**Comment by apotonick** [comment]
This might probably come from using Reform 2.1 which doesn't support multiple validations anymore (because: wrong). Can you make sure to link the Reform version you're using and also that you're **not running** the same op instance twice in your test?

A minimal example would be helpful, too! Thanks. :beers:

**Comment by johnlane** [comment]
I have `reform (2.1.0)` and I am pretty sure I am not running the same op instance in my test. I have reproduced the problem in a [test app](https://github.com/johnlane/trailblazer-issue109) and have identified that it occurs when the contract is defined using the form:

    class Form < Reform::Form
    ...
    end
    contract Form

instead of the traditional

    contract do
    ...
    end

I was doing the former so that the contract class isn't anonymous and my reason for doing so was to allow me to provide a named path to translations for error messages like I discussed a while back on [Trailblazer#77](https://github.com/apotonick/trailblazer/issues/77).

Test output:

    1) Failure:
    CrudTest#test_0001_anonymous [/home/john/files/interest/computer/work/git/test-apps/trb109/test/concepts/testthing/crud_test.rb:7]:
    --- expected
    +++ actual
    @@ -1 +1 @@
    -"{:item=>[\"can't be blank\"]}"
    +"{:item=>[\"can't be blank\", \"can't be blank\"]}"

    1 runs, 2 assertions, 1 failures, 0 errors, 0 skips

**Comment by iJackUA** [comment]
Had the same issue with `reform` 2.1
added `gem 'reform-rails'` that updated `reform` to 2.2 and the issue seems to go away. 
@apotonick maybe this issue is already outdated and fixed
