### ISSUE TITLE
[Discussion]  introduce context object

### ISSUE THREAD

**Issue by blelump** [trailblazer/trailblazer#116]
Hi,

I'm thinking about introducing a context object in operations as it would lerevage its features and leave params variable 'as is,  without decorating it with additional data , eg. `current_user`. 

The context object would be anything that responds to `:[]` operator and returns non nil value for `ctxt [:params]`. Additionally, if policy is being used, it returns `current_user` as well.

Whats your thoughts about that @apotonick ?

**Comment by apotonick** [comment]
This now exists! http://trailblazer.to/gems/operation/2.0/api.html#result-object
