### ISSUE TITLE
Reject should have same return style as run

### ISSUE THREAD

**Issue by johnlane** [trailblazer/trailblazer#121]
When using the _run style_ to invoke an operation, the `run` and its negative `reject` differ in how they return status. The `run` returns a `[result, operation]` pair whereas the `reject` only returns the operation and not the status.

I think it would be better if these were consistent.

I guess changing this would have too wide an impact on existing usage, but I thought I'd mention it anyway.

**Comment by apotonick** [comment]
This method doesn't exist in TRB2 anymore.
