### ISSUE TITLE
operation.success? and operation.fails?

### ISSUE THREAD

**Issue by sveredyuk** [trailblazer/trailblazer#131]
@apotonick 
I am working not with operations. Great feeling. 
But I found that missed some comfortable predicates which give me an answer on the question: "Was this operation success?". Something like `op.success?` and `op.fails?`. 

I know, we have `.valid?`.. but valid? it's about data.

And for test it will be much more semantic:

``` ruby
it 'success' do
  result, op = Blah::Create.run(name: 'Yes')

  res.success?.must_equal true # better semantic for succeeding of the operation
end

it 'fails'
  result, op = Blah::Create.run({})

  res.fails?.must_equal true
```

May I work on the implementation of this ?

**Comment by apotonick** [comment]
Hmm.. it's not defined in TRB what is "successful" - the idea is to make the op `invalid!` whenever something went wrong. This "merges" validation or processing error and reflects the flag you're asking for, doesn't it?

If one needs further messages, they have to be exposed manually.

My idea here is to keep the API to a minimum of methods - the more we add, the more can go wrong! What I **do** think would be cool to have is a real result object, but I honestly haven't had the need, yet.

**Comment by sveredyuk** [comment]
@apotonick `ResultObject` i also thought about this. Will be more logical if result has `success?` or `fails?` method and reasons.... why it fails? something like errors for invalid data, we could add messages of fails reason. Now I am using operations not only for data validations and persists, but trigger other operations to organize them in operations-chain. The main ideas is to have something like this:
```ruby
class Project
  class ChangeOwner < Trailblazer::Operation
    def process
      chain do
        StepOne
        StepTwo
        StepThree
      end
  end
```
It's almost like transactions, but...
All steps inside chain must return result object with `success = true #=> success?` or `false #=> fails?`. If we got first fails, the chain will return the report with description of which step failed. Also, we could return fails reason, because step could have few reasons to fail. It's crazy stuff, but it will give you total control of the business process and in general at scopes (chains) of processes, provide normal communication backend process with frontend messages.

I could try with implementation with this scenario. If you wish.

**Comment by fmnoise** [comment]
@sveredyuk your examples are validations by their nature
> new_owner.nil?
> project.owner == new_owner

so terms valid\invalid still have sense in this context
but I agree for error messages, that would be really helpful to pass such info to user

**Comment by sveredyuk** [comment]
@fmnoise It's important to understand that if you bring some architecture to the project, you must be consistent and don't allow born of indirection layers. If I pick trailblazer, it must cover 100% of business functionality besides router and controller. Now in my app with trailblazer to the concept, I also implement such layers as `Finder` - responsible for finding data, less logic in the model  and `State` - responsible for knowledge about object state and how to change it. Looks nice, will see how it will help in the future.

**Comment by apotonick** [comment]
@sveredyuk I want to integrate transaction pipelines e.g. from http://dry-rb.org/gems/dry-transaction/ into the `Operation` exactly as you suggested it! Maybe we can brainstorm this week? Given the complexity of the transaction chain, a result object would make a lot of sense, and could have additional methods such as `success?`, instead of adding all that on the operation. :beers: 

Your `Finder` and `State` sounds like something I always wanted to add, too!!! I would love to see how you do this right now, let's chat on Gitter?

**Comment by apotonick** [comment]
We now have the `Result` object for transporting state: http://trailblazer.to/gems/operation/2.0/api.html#result-object

Internal flow can be handled via the `Pipetree`: http://trailblazer.to/gems/operation/2.0/pipetree.html

This is how the result can be interpreted in an HTTP environment: http://trailblazer.to/gems/operation/2.0/endpoint.html

**Comment by sveredyuk** [comment]
@apotonick awsome!
