### ISSUE TITLE
Using named parameters with #process doesn't work with Rails (HashWithIndifferentAccess)

### ISSUE THREAD

**Issue by contentfree** [trailblazer/trailblazer#132]
I came across @apotonick suggesting that he's been doing something similar to this in his operations:

``` ruby
class MyOp < Trailblazer::Operation
  def process(my_object:, **params)
    validate(my_object) do
      # .. etc
    end
  end
end
```

This works nicely when you call the operation with symbol keys. However, Rails (and web frameworks in general perhaps?) either use string keys or HashWithIndifferentAccess which does not work with Ruby's named parameters (see https://bugs.ruby-lang.org/issues/9731).

Could `trailblazer/operation.rb#run` symbolize the keys of `@params` before calling `#process`?

**Comment by rmontgomery429** [comment]
I ran into a similar issue when switching from active model validations which had symbol keys to dry validation which had string keys.

**Comment by apotonick** [comment]
There's no easy way for a fix, in TRB2 the `Contract::Validate`'s `:key` option [takes care of this](http://trailblazer.to/gems/operation/2.0/contract.html#extracting-params) for you.
