### ISSUE TITLE
When including Model, a blank process method is still needed

### ISSUE THREAD

**Issue by dvandersluis** [trailblazer/trailblazer#137]
Consider a show operation:

``` ruby
class Show < Trailblazer::Operation
  include Model
  model User, :find
end
```

In this case, I don't have any processing to do in the operation, I just want to find the record and show it (perhaps with a representer).

However, as is, when I call `respond User::Show` or `run User::Show`, it crashes with `undefined method 'process' for #<User::Show:0x007f905b22d8f8>`, unless I add an empty `process` method (unlike page 258 of the book).

I think this can be fixed simply by adding an empty `process` method to `Trailblazer::Operation::Model`.

**Comment by apotonick** [comment]
In 2.0, you won't have to do this anymore.
