### ISSUE TITLE
Preferred way of collecting exceptions that occur in an Operation?

### ISSUE THREAD

**Issue by mcmire** [trailblazer/trailblazer#142]
I've been starting to use operations in my app and I've run into something I need some clarification on. In the process of running an operation, it is completely possible to encounter an exception. For instance, say you're doing some Stripe-related things in your operation and Stripe gives you an error. The problem I am encountering is that I still need access to the form object in my controller. As a contrived example:

``` ruby
class SomeController < ApplicationController
  def create
    operation = SomeOperation.(params)
    redirect_to action: :index
  rescue Trailblazer::Operation::InvalidContract
    render :new,
      locals: { form: operation.contract, error: "Some part of the form was invalid" },
      status: 422
  rescue => error
    render :new,
      locals: { form: operation.contract, error: "Something bad happened" },
      status: 500
  end
end
```

Because the operation raises an exception, `operation` is nil and we don't have access to the contract.

Is there a way to instantiate the operation first and then call `call` on it? Alternatively, is there a way to pass the form object into the operation? Alternatively alternatively, perhaps there's a way to tell the operation _not_ to raise an InvalidContract? (This way I could just capture all exceptions in the operation itself.)

**Comment by mcmire** [comment]
After some thought, what I've come up with is using a combination of `Operation.run`, the non-block form of `validate`, and then rescuing exceptions in the operation itself, like this:

``` ruby
class SomeController < ApplicationController
  def create
    successful, operation = SomeOperation.run(params)

    if successful
      # handle success
    elsif operation.errors.any?
      # handle validation errors
    else
      # assume operation encountered an exception
      # and do something with operation.captured_exception
    end
  end
end

class SomeOperation < Trailblazer::Operation
  include Model
  
  contract SomeForm
  model SomeModel, :create   # or whatever

  attr_reader :captured_exception

  def process(params)
    if validate(params[:something])
      # save the contract, or do whatever
    else
      notify!
    end
  rescue => exception
    @captured_exception = exception
    # handle the error somehow
  end
end
```

This feels fine to me, although I'm curious if there are other ways of doing this.

**Comment by apotonick** [comment]
In 2.0, no exceptions are raised anywhere from Trailblazer! The second form is the way I normally do it, too (e.g. with Stripe for Trailblazer PRO). I played with different ways to abstract that in TRB itself but ended up with more code than I had when catching things manually, so I'll leave this up to you for now!

Good points, though! :beers:

**Comment by mcmire** [comment]
@apotonick Ah, yes, I guess in the second case I'm no longer rescuing InvalidContract. So does that mean there's no point in calling `notify!` in my operation? When using `.run`, what determines whether the first return value will be true or false?

**Comment by apotonick** [comment]
Calling `notify!` makes sense if it's a "callback". `::run` right now uses the `@valid` flag. As I said, in TRB 2, this is all super simplified.

**Comment by mcmire** [comment]
Okay. That's good to know, although at the moment I have to make something work with TRB 1. It turns out that the solution I posted before didn't quite work. I didn't realize that `run` doesn't actually care about the return value of `process` -- if `validate` (really `valid?`) returns true, then the result that the operation returns is always true. I guess what I could do is that instead of raising an error inside of operations, I could use `invalid!` to force the result of the operation to be false, perhaps even setting an instance variable, and then checking that in the controller. Like this:

``` ruby
class SomeOperation < Trailblazer::Operation
  include Model

  contract SomeForm
  model SomeModel, :create   # or whatever

  attr_reader :captured_exception

  def process(params)
    if validate(params[:something])
      # save the contract, or do whatever
    end
  rescue => exception
    @captured_exception = exception
    # handle the error somehow
    invalid!
  end
end
```

Does this seem like a good approach?

**Comment by apotonick** [comment]
Should work!
