### ISSUE TITLE
Dependency conflict with trailblazer-cell

### ISSUE THREAD

**Issue by BrunoSalerno** [trailblazer/trailblazer#146]
It looks that there is a dependency conflict between the last versions of trailblazer and trailblazer-cells gems.
Trailblazer-cell (in all versions) requires cell `< 5.0.0, >= 4.1.0.rc1`, which in turn requires gem uber `< 0.2.0, >= 0.1.0`. But the last version of trailblazer (1.1.2) requires uber `< 0.1.0, >= 0.0.15`.

This might be related to f3eb9f08e9d76a091a3b41de442b0aa5702bba6b

**Comment by apotonick** [comment]
Lock it to cells-4.1.3.

**Comment by apotonick** [comment]
Actually, I could yank 4.1.4 and release 4.2 instead?

**Comment by BrunoSalerno** [comment]
@apotonick it sounds good ;) Otherwise I could lock it to cells 4.1.2, right
