### ISSUE TITLE
Naming of Step Operators

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer#148]
As the TRB2 release is coming closer, users start to play with the new API and were unhappy about the naming of the pipetree operators. Suggestions welcome. Of course, the "low-level" cryptic operators will stay, but will be aliased.

| Operator | What it does | Suggested name |
|--------------|----------|----------|
| `self.|` | Runs the passed step macro which in turn adds its steps to the track(s). | `step` |
| `self.>` | Adds step to right track | `right` or `continue` | 
| `self.<` | Adds step to left track | `left` or `error` |
| `self.&` | Adds step to right track and jumps to left if result falsey. | `consider` |
| `self.%` | Adds step to both tracks | `whatever` |   

Thanks to @acaron and the Shopify team for most of these suggestions! :beers:

**Comment by soulcutter** [comment]
`%` could be `error_and_continue` ?

**Comment by apotonick** [comment]
@soulcutter We should try to reflect the two-tracks nature of the pipe more in the method names. Keep it coming!!!

**Comment by krisleech** [comment]
I'd say `left` / `right` are the least helpful, because you have to remember which is which, but okay as aliases.

`success` for `>`
`failure` for `<`
`both`, or `success_or_failure` for `%`.

Not sure what `&` is used for but `success_inverted` maybe.

**Comment by apotonick** [comment]
I know what you mean, @krisleech but on the other hand, I want users to maintain the mental "left/right track" model in mind, also because the visualization is left/right.

Difficult, difficult, ...

**Comment by apotonick** [comment]
I like 
`success` and 
`failure`

**Comment by acaron** [comment]
I like `failure`, but I prefer `continue` over `success`. For me, `success` suggest a final answer instead of `continue` which says continue if there is no failure or go to the next step. As for `left/right`, the symbol `>/<` already means the same thing, do we need to have it as a word? Thanks for the alias :D

**Comment by krisleech** [comment]
>  I want users to maintain the mental "left/right track" model in mind

I do like the railway concept, visually and the idea of tracks. But even in the pictures I have seen it is more like continue and divert. Continue being the happy path and divert being the unhappy path. 

![18832](https://cloud.githubusercontent.com/assets/66143/21007702/f43f90e2-bd35-11e6-9423-3dba2a5c6bea.png)

>  For me, success suggest a final answer instead of continue which says continue if there is no failure or go to the next step

Fair point. I see it as lots of little successes.

 > Difficult, difficult, ...
 
I don't think you are going to please everyone :)

**Comment by acaron** [comment]
@krisleech I really like `continue` and `divert`!

**Comment by fran-worley** [comment]
@acaron FWIW I like continue and divert! Embrace the train 🚂 which might change course for reasons other than failure/error.

I think we should steer clear of left and right as in theory you could end up with more than two tracks and it could then become hard to visualize.

Linguists might complain that your whatever could arguably be whichever given that your referencing a defined set of options (your tracks, or step success). Not being a linguist I personally prefer whatever. I guess that's what spending the weekend with 3 English language teachers does to you!!

**Comment by apotonick** [comment]
Thanks for all the input! :heart:
