### ISSUE TITLE
Is it a good idea to test step method of operation?

### ISSUE THREAD

**Issue by quolpr** [trailblazer/trailblazer#151]
For example, we are having such operation:
```
class Create < Trailblazer::Operation
  step :heavy_logic!

  def heavy_logic!(options, **)
    # Some logic here
  end
end
```

And I am testing`heavy_logic!` method, in such way:
```
RSpec.describe Session::Create do
  let(:operation) { Session::Create.new({}) }

  describe '#heavy_logic!' do
    subject { operation.heavy_logic!(options) }
    let(:options) { {} }

    it 'tests heavy logic' do
      expect(subject).to eq 1
    end
  end
end
```

Is it a good idea? Or maybe it will be better if I will extract `heavy_logic!` to the new class? What is canonical way?

**Comment by apotonick** [comment]
Either extract the step to a [callable object](http://trailblazer.to/gems/operation/2.0/api.html#step-implementation) that can be tested without the op, or test the entire method - in no way should you call this method from the outside, creating operation instances is highly illegal! :grimacing:

**Comment by quolpr** [comment]
> creating operation instances is highly illega
I have such thought too, that why I have created this issue, to confirm it :)

Do you, where should I keep callable objects? I am having the rails dir structure(not concepts). I was thinking about `app/services`, but operations are already service objects and I will be having 2 dirs, which are storing services(`app/services` and `app/operations`) - I think it is not good.

**Comment by apotonick** [comment]
We put them in `app/concepts/comment/lib/whatever.rb`.

**Comment by quolpr** [comment]
But what about projects without concept dir structure? Do you have any idea where to store it? Just in `/lib`?

**Comment by apotonick** [comment]
No idea, there's a reason we introduced the TRB file structure :joy: we don't have to think about this anymore. What keeps you from introducing it?

**Comment by quolpr** [comment]
A habit I think :) But the TRB file structure seems to be sweet. Will try to use it, thanks for your help!

**Comment by apotonick** [comment]
You won't regret it. Let me know if you need help.

How are you liking TRB2 so far?

**Comment by quolpr** [comment]
I had used only operations and I can say that flow control is a very good idea, very like it! Now I am not needed to do something in `process` method - very cool, I like declarative way.
And `Wrap` is a good idea too! Now I can easily make some operations in SQL transactions. Overall, you are having a good course. Thank you for your job!
