### ISSUE TITLE
Make nested macro more flexible

### ISSUE THREAD

**Issue by quolpr** [trailblazer/trailblazer#153]
There are many places, where I am just calling another operations:
```ruby
class Session::Operation::Create < Trailblazer::Operation
  step :encode_token

  def encode_token(options, params:)
    result = Token::Operation::Encode.(
      user_id: options['user'].id
    )
    options['another_token'] = result['token']
    result.success?
  end
end
```
And I can make it with `Nested`, but as I understand it doesn't support custom mapping. And I can't specify the arguments of nesting operation.
I suggest to make such DSL:

```ruby
class Session::Operation::Create < Trailblazer::Operation
  step Nested(
    Token::Operation::Encode,
    # It maps result from executed operation to current operation options.
    result_map: -> (options, result) { options['token'] = result['another_token'] },
    # It returns argumetns for operation. First element is params, the second is options. 
    # If options or params are not present nil must be setted.
    args: -> (options) { [ { user_id: options['user'].id }, { some_option: true } ] }
  )
end
```

@apotonick what do you think? If it is ok I can make it.

**Comment by apotonick** [comment]
Cool idea! I was thinking of something like 

```step
step Callable(MyCallable, result: "result.mycallable")
``` 

Where `MyCallable` will be invoked and the result automatically stored in `"result.mycallable"`. This is a bit what you're suggesting (only a subfunction, though).

Can I see some examples of how you use those `Nested` operation calls, please?

**Comment by quolpr** [comment]
@apotonick I understood that I am using `Nested` in a wrong way. Now I am working on `Callable` macro, do you mind?

**Comment by dnd** [comment]
This was a proposed implementation from a gitter discussion:
`Nested(SomeOp, results: (true('results.some_op') | 'results.some_other_name'), capture: ['some_op_value', 'some_op_value2', ...] | {'some_op_value' => 'current_op_key'})`

`capture` could also take an `:all` symbol to obviously store all result keys. a decision would have to be made about how to deal with identical keys.

This does not have provisions for altering the data that is sent to `SomeOp` though that could be added in a fashion similar to `capture`. 

This whole thing does lead to the potential of a very long step definition. Whether that's good or bad I don't know, but this does cover the likely usages.

**Comment by apotonick** [comment]
Hey, this is now implemented: 

* http://trailblazer.to/gems/operation/2.0/api.html#nested-input
* http://trailblazer.to/gems/operation/2.0/api.html#nested-output

Happy to discuss a nicer API on top of that! :beers:

**Comment by apotonick** [comment]
@quolpr What happened to the `Callable` macro? :thinking:
