### ISSUE TITLE
Test 2.0.1, please.

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer#162]
Any chance to have a quick test run for 2.0.1?

@mensfeld @dnd @cdennl @lucas-aragno

Here's the `Gemfile`:

```
gem "trailblazer", github: "trailblazer/trailblazer"
gem "trailblazer-operation", github: "trailblazer/trailblazer-operation"
gem "pipetree", github: "apotonick/pipetree"
```

**Comment by mensfeld** [comment]
@apotonick  apart from some internal stuff that we were talking about everything works for me and my cases! :+1:  great job!

**Comment by apotonick** [comment]
Thanks! :heart_eyes:
