### ISSUE TITLE
Nested operations only pass options in one direction

### ISSUE THREAD

**Issue by georgemillo** [trailblazer/trailblazer#166]
When I nest an operation in another operation, the outer operation has access to any options that are set within the nested one:

```ruby
class Inner < Trailblazer::Operation
  step :set_option

  def set_option(options)
    options['test'] = 'it works!'
  end
end

class Outer < Trailblazer::Operation
  step Nested(Inner)

  step :log_option

  def log_option(options)
    puts options['test']
  end
end

Outer.()
# "it works!"
```

But the inner operation doesn't seem to have access to the outer op's options:

```ruby
class Inner < Trailblazer::Operation
  step :log_option

  def log_option(options)
    puts options['test']
  end
end

class Outer < Trailblazer::Operation
  step :set_option
  step Nested(Inner)

  private

  def set_option(options)
    options['test'] = 'it works'
  end
end

Outer.()
# (nothing)
```

Is this a bug, or a feature?

**Comment by apotonick** [comment]
Actually, a bug. Thanks for reporting!

**Comment by georgemillo** [comment]
Temporary workaround. Note that `stringify_keys` is only available if you're using ActiveSupport:

```ruy
class Inner < Trailblazer::Operation
  step :log_option

  def log_option(options)
    puts options['test']
  end
end

class Outer < Trailblazer::Operation
  step :set_option
  step :nest_inner

  private

  def set_option(options)
    options['test'] = 'it works!'
  end

  def nest_inner(options)
    result = Inner.({}, options.to_hash.stringify_keys)
    options['test'] = result['test']
  end
end
```

(Why does `options.to_hash` return a hash with symbol keys anyway? Wouldn't it make more sense to use strings, since that's what's used elsewhere?)

**Comment by apotonick** [comment]
I revisited that code, and actually, this is per design: https://github.com/trailblazer/trailblazer/blob/master/test/docs/nested_test.rb#L88

Let me think about it for a bit.

**Comment by apotonick** [comment]
BTW, `Options#to_hash` is a **private** concept and returns symbols for the KW args mechanics.

**Comment by georgemillo** [comment]
Thanks for the speedy response and the work on the `inner` option, but I'm wondering what the reasoning is behind not "leaking" state from an outer operation into an inner one? Since posting the above issue I've already run into the same problem in a different part of my codebase (while upgrading from TRB 1 to 2), in this case because Nested doesn't pass the `params` down from my controller. I think it's reasonable to expect that the inner operation would also want access to my controller params by default, without having to add a bunch of boilerplate.

If `step Nested(Inner)` doesn't pass in any `options`, that seems to contradict the general principle of how `step` and the pipetree work: that `options` gets "passed from step to step" and that an operation "maintain(s) only one stateful object" (those are quotes from the docs [here]). In a pipetree like this:

```ruby
step :step_1
step :step_2
step :step_3
```

... options get passed through through the steps in a simple, easy-to-understand fashion, and I can update options with `step_1` knowing that the later steps will see my changes. But say I decide to refactor and extract `step_2` to its own op which I now nest:

```ruby
step :step_1
step Nested(Step2)
step :step_3
```

... this looks to the unexperienced eye like it would work as before, but actually it will break everything and I have to add a bunch of boilerplate (like my workaround code above, or the new `inner` arg) just to get the behaviour that normally happens by default.

Sorry for writing such an essay!

**Comment by apotonick** [comment]
I understand, essays are necessary here because it's a very difficult topic. Actually, hang on, `params` should be available in `Nested`.

The idea is that, for example, the outer operation already assigns `contract.default`, this shouldn't be passed into the nested op, as it might override it. For that reason I decided that mutable data is not passed in per default.

**Comment by apotonick** [comment]
I don't know what went wrong on your side @georgemillo, but `params` get passed through (of course). Only mutable data from the outer operation is considered private.

**Comment by georgemillo** [comment]
Yeah, not sure what I was doing wrong with `params`, it seems to be working actually.

I hope I'm not belabouring the point, but maybe it would help if I explained the actual use case that got me thinking about this:

My app is divided into two parts, a 'main' app for regular users, and an admin interface. Users can create a `Card`:

```ruby
module Card
  class New < Trailblazer::Operation
    extend Contract::DSL
    contract ::Card::Form

    step :setup_model!
    step Contract::Build()

    private

    def setup_model!(opts, params:, user:, **)
      opts['model'] = user.cards.new
    end
  end
end
```

`user` in this case is passed in from the controller, not from the params, because users can only add cards to their own account

Admins, on the other hand, can add a card to *anyone's* account, so the params contain `user_id`, and intuitively I'd expect to be able to do something like this:

```ruby
module Admin
  module Card
    class New < Trailblazer::Operation
      step :setup_user!
      step Nested(::Card::New)

      private

      def setup_user!(opts, params:, **)
        opts['user'] = User.find(params[:user_id])
      end
    end
  end
end
```

Essentially, I'm setting a 'default' value for user in the inner op, and other ops that use it can then override that default. But it doesn't work, because `options` doesn't get passed into the nested option. In my opinion, this is a bad idea because it means that **`step Nested(Op)` is fundamentally different from any other call to `step**. On all other occasions, when I call `step` (or `success` or `failure`) I expect that it will receive the options object generated by the previous step, but with Nested I get a totally new options object.

I don't know why it's such a bad idea to pass the options from the outer op to the inner op anyway - surely if I'm using the inner op at all, I'm already thinking about what `options` it sets, and if I use an option with the same key it's more likely to be a conscious decision than an accident. I can imagine there *are* scenarios where I want to avoid passing a key in, but I'd rather have a blacklisting approach than a whitelisting approach.

---

Anyway, sticking with the existing `inner` implementation, if I understand things correctly then my above example should be written like this:

```ruby
module Admin
  module Card
    class New < Trailblazer::Operation
      step :setup_user!
      step Nested(::Card::New, input: -> (opts) do
        { 'user' => opts['user'] }
      end)

      private

      def setup_user!(opts, params:, **)
        opts['user'] = User.find(params[:user_id])
      end
    end
  end
end
```

This is pretty ugly, and it's a lot of boilerplate just to say 'pass `options['user']` into the nested op'. If you want to keep the 'nothing passed into Nested by default' approach, how about extending things so that `input` can be passed an array of strings as well as a block? If it's an array of strings (or, I suppose, just a single string if you only want one key), it means "these are the keys within `options` that I want to pass into the nested op". So I could simplify the above to:

```ruby
module Admin
  module Card
    class New < Trailblazer::Operation
      step :setup_user!
      step Nested(::Card::New, input: 'user') # or ['user', 'other_key_i_want_to_pass']

      private

      def setup_user!(opts, params:, **)
        opts['user'] = User.find(params[:user_id])
      end
    end
  end
end
```

... then if I want more fine-grained control over what keys to pass in, I can use a block for the existing behaviour.

What do you think?
