### ISSUE TITLE
Can `Trailblazer::Operation::New` be renamed?

### ISSUE THREAD

**Issue by georgemillo** [trailblazer/trailblazer#168]
I just got a weird error when trying to do something like this with nested operations:

```ruby
class Widget < ApplicationRecord
  module Operations
    class New < Trailblazer::Operation
      extend Contract::DSL
      contract MyContract

      step Model(Widget, :new)
      step Contract::Build()
    end
  end
end

class Widget < ApplicationRecord
  module Operations
    class Create < Trailblazer::Operation
      step Nested(New)
      step Contract::Validate()
      step Contract::Persist()
    end
  end
end

Widget::Operations.Create(params)
# => NoMethodError Exception: undefined method `new' for #<Trailblazer::Skill:0x007fde75e54510>
```

After stepping through the code with byebug, I realised that the problem is that `Nested(New)` gets resolved to `Trailblazer::Operation::New`, rather than `Widget::Operations::New` like I expected.

I *could* fix this by renaming `New` to something else, or by being more explicit (`step Nested(Widget::Operations::New)`) but this feels like a gigantic violation of the Principle Of Least Astonishment, and `New` will surely be a common name that many people will want to use for an operation, since it's one of the basic RESTful method names encouraged by Rails, and the Trailblazer docs [encourage](http://trailblazer.to/gems/operation/2.0/api.html) the use of `Edit`. as an operation name, sister of `New`. (EDIT: looks like `New` as an operation name was semi-officially endorsed [here](https://github.com/trailblazer/trailblazer/issues/156) as well.)

`Trailblazer::Operations::New` is defined [here](https://github.com/trailblazer/trailblazer-operation/blob/v0.0.10/lib/trailblazer/operation/pipetree.rb#L13) and doesn't appear to be part of the public API, right? Could it be renamed, perhaps to something like `NewProc`, to lower the possibility of this ugly naming clash in the future?

**Comment by apotonick** [comment]
I agree, we should rename `Operation::New`, it's a completely internal thing anyway.

Thanks @georgemillo!
