### ISSUE TITLE
[RFC] Blindly call object instead of Uber::Callable

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer#171]
Instead of checking for `is_a? Uber::Callable` in `Trailblazer::Option`, we could simply check `is_a?(Symbol)` and, if not, blindly `call` whatever was passed into. This makes the public API simpler.

The only caveat is if someone has a callable symbol, which... would be quite odd, wouldn't it?

**Comment by mensfeld** [comment]
If someone has a callable symbol then it must be a flaw in his design

**Comment by apotonick** [comment]
Haha, true.

Let's remove the need for `include Uber::Callable` then! :ship:

**Comment by apotonick** [comment]
This is implemented in `operation-0.1.0`.
