### ISSUE TITLE
Constant resolution breaks explicit contract definitions

### ISSUE THREAD

**Issue by adrianpacala** [trailblazer/trailblazer#172]
Using Ruby `2.4.0`, the [example code](http://trailblazer.to/gems/operation/2.0/contract.html#definition-explicit):

```ruby
module Song::Contract
  class Create < Reform::Form
    # ...
  end
end

class Song::Create < Trailblazer::Operation
  # ...
  step Contract::Build( constant: Song::Contract::Create )
  # ...
end
```

raises the following error: ````<class:Create>': undefined method `Build' for Song::Contract:Module (NoMethodError)````.

Using `step self::Contract::Build( constant: Song::Contract::Create )` (or `  step Trailblazer::Operation::Contract::Build( constant: Song::Contract::Create )` instead fixes the problem.

**Comment by apotonick** [comment]
Oh, nice, more and more breakage in Ruby 2.4! :grimacing: Did they change anything in namespacing? I stopped following after Ruby 2.1 because all they added was bullshit so far.

**Comment by mensfeld** [comment]
:+1 I have similar problems

**Comment by ushis** [comment]
Just a note: This only happens, when Song is a module.

**Comment by Mehonoshin** [comment]
I'm having similar behavior at ruby '2.3.4'
