### ISSUE TITLE
[Feature request] Pundit policies with other values than model

### ISSUE THREAD

**Issue by mensfeld** [trailblazer/trailblazer#173]
I this common case that pundit policy should be invoked not on ```options['model']``` but on something else (```options['repository']``` for example). Maybe there could be an option to specify the model for pundit:

```ruby
step Policy::Pundit( MyPolicy, :create?, model_key: 'repository' )
```

**Comment by apotonick** [comment]
What if we'd document how to write your own policy classes? It's actually super simple. Would that be better?

**Comment by mensfeld** [comment]
Yeah - I don't need this feature on my own as I implemented policies on my own BUT I would still find that or a doc useful as quite often you don't check policy for a resource but for example its parent.

**Comment by rishirajkumar97** [comment]
@apotonick  can you please point me such documentation?

**Comment by Tab10id** [comment]
At actual trailblazer version you can use original macro:
```ruby
step Policy::Pundit(MyPolicy, :create?),
        input: ->(_ctx, repository:, current_user:, **) { {model: repository, current_user: current_user} }
```

**Comment by apotonick** [comment]
Or even simpler

```ruby
step Policy::Pundit(MyPolicy, :create?),
     In() => {:repository => :model}, In() => [:current_user]
```

Here are preview docs: https://ornate-heliotrope-1c15e2.netlify.app/2.1/docs/activity#activity-variable-mapping

**Comment by mensfeld** [comment]
Going to close this one and call it stale after 5 years.

Cheers :beer: Nick!
