### ISSUE TITLE
Why has Operation.run() been removed? Is there still a way to make an operation raise an error on failure?

### ISSUE THREAD

**Issue by georgemillo** [trailblazer/trailblazer#174]
Just wondering why Operation.run() has been removed in TRB 2?

I understand the conceptual reasons why you don't normally want to raise an error when an operation fails, but I can think of one situation where it's very helpful to do so: in tests. Say I'm following the advice in the TRB book and using operations to create my sample data:

```ruby
let(:post) { Post::Create.(title: 'hello')['model'] }

example 'updating the title' do
  Post::Update.(id: post.id, title: 'guten tag')
  expect(post.reload.title).to eq 'guten tag'
end
```

I **know** that `Post::Create` should succeed here. If it fails, that means I've either written the test wrong (maybe posts have a required attribute called `content` that I forgot to add), or something unrelated has changed since I wrote the test (maybe the validations in `Post::Create` have since changed, but I forgot to update the test). If `Post::Create` fails here, it's genuinely an exceptional condition, and it makes sense to raise an exception so I can spot the problem immediately.

If the operation fails silently then you can get some unintuitive errors. For example, if `Post::Create` fails above, RSpec will set `post` to `nil`, then trundle on obliviously until it tries to call `post.id`. Boom - NoMethodError, but when I look at the failing test, it's not immediately clear what I did wrong. But it *should* be clear, because c'mon, all I'm doing is creating some test data, and with ActiveRecord I could guard against these issues with just one extra keystroke (calling `create!` instead of `create`).

Maybe, in fact, a better name than `run` would be `call!`, as it follows the Ruby convention of using `!` for 'dangerous' methods, and follows the same pattern that most Ruby devs are used to with `create` and `create!` in AR. The guides can discourage the use of `call!` and explain why it's generally a better idea to use proper error handling with `failure` etc., but I think it's worth keeping the method around for the cases where it is helpful.

**Comment by apotonick** [comment]
`Operation#call` is the only way to run an operation. The exception was only helpful in tests, and we will soon have `trailblazer-test`, which runs the op for you and throws an exception should it have failed. 

That reduces core code and *a lot* of confusion.

**Comment by georgemillo** [comment]
Nice; good to know that this feature is coming back. If there's anything I can do to help with `trailblazer-test` please let me know.
