### ISSUE TITLE
Model step macro : also allow find_by something else as 'id'

### ISSUE THREAD

**Issue by pvmeerbe** [trailblazer/trailblazer#179]
Currently the Model step macro allows for find & find_by(id: ...)

However I also often use the case
    
    find_by(something_else: ...) 

Can this also be added?

thanks

**Comment by apotonick** [comment]
It's easily added but I'm skeptical because the code added is more than the actual self-made implementation?

**Comment by pvmeerbe** [comment]
I currently idd have my own implementation for this. It just seemed more logically to group them into Model & to offer them as a more complete set. I'll stick to my own implementation if you feel it clutters the trailblazer code too much.

**Comment by apotonick** [comment]
You wanna PR? :grimacing:

**Comment by pvmeerbe** [comment]
I'll try to create something next Tuesday. I currently have separate steps for each find_by scenario.
To create a more global solution, somehow the specific keys and values to perform the find action should be declared/retrieved. 

Solutions I can think of right now:

- keys specified in the step DSL  + actual values to use retrieved from the params,ex

      step Model( BlogPost, :new , [:author_name,:author_whatever,...])

- keys and values retrieved from the options[:param] , if so I guess it should be nested somehow in params to easily grasp the find_by data?
- .. other solutions?

First solution requires to make the 'action' param of the DSL mandatory
Second solution requires to introduces a special key to identify the nested find_by data

Should these find_by keys be specified during runtime based on Operation input? Or can they be configured statically in the operation via the step DSL? Until now I only needed the static case...

**Comment by marctich** [comment]
@apotonick this can be closed, as they can now use find_by with any key they wish using trailblazer-macro, and any new discussions (or issues) should be there.

**Comment by konung** [comment]
FYI: there is also now https://github.com/trailblazer/trailblazer-finder for more complex searches and lookups ( not just a simple Model lookup)

**Comment by somenugget** [comment]
@marctich how do you think, is support of `find_by!` is also needed?
Currently, `step Model(Song, :find_by, :title )` will call `Song.find_by(title: 'song title')`.
But `step Model(Song, :find_by!, :title )` will call `Song.find_by!('song title')` which will throw an `ActiveRecord::StatementInvalid`.
I can add `find_by!` support if it makes sense 😊
