### ISSUE TITLE
File Upload Fails with No such file or directory

### ISSUE THREAD

**Issue by HirenBhalani-Bacancy** [trailblazer/trailblazer#181]
I am trying to upload .jpg file using 
```
simage = params[:image]
Trailblazer::Operation::UploadedFile.new(simage, tmp_dir: "/tmp/uploads").to_hash
```

Here, `params[:image]` contains FILE object of `ActionDispatch::Http::UploadedFile`

But, It throws following error each time :

> No such file or directory - /tmp/uploads/RackMultipart20170306-4893-1f6sc1p20170306-4893-b37h25

**Comment by apotonick** [comment]
Hi, the `UploadedFile` class is not supported anymore, you can use something like Shrine instead.

**Comment by HirenBhalani-Bacancy** [comment]
@apotonick  :  Thanks for Update 👍

**Comment by janko-m** [comment]
@HirenBhalani-Bacancy Shrine has the `rack_file` plugin that allows you to upload the Rack uploaded file hash directly (Shrine will then internally convert it into an IO-like object, and extract the original filename and content type information from the hash).
