### ISSUE TITLE
Add fast track connections only on demand?

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer#188]
With TRB 2.1 around the corner, we have the chance to simplify the internal circuits if we introduce a new option and break old code that uses `Railway.pass_fast!` and `Railway.fail_fast!`.

## Not using fast track

Here's an operation that doesn't use the `FastTrack` feature, which allows you to end the operation from a specific step by [returning `Railway.pass_fast!` or `Railway.fail_fast!` from a step](http://trailblazer.to/gems/operation/2.0/api.html#flow-control-fail-fast).

```ruby
class Create < Trailblazer::Operation
  step :a
  fail :b
  step :c
  step :d
end
```
The circuit (2.1) will look as follows.

![image](https://user-images.githubusercontent.com/10406/29006335-e63dc36c-7aed-11e7-823e-e26710ae2663.png)

With the `FastTrack` feature enabled (and that's the case per default), we have to connect all "boxes" (_tasks_) with the fail_fast and pass_fast end to allow *potentially* emitting the `Railway.pass_fast!` or `Railway.fail_fast!` signal. This leads to a more complicated circuit.

![image](https://user-images.githubusercontent.com/10406/29006357-2d411782-7aee-11e7-8762-aac9a85f5707.png)

My idea was to **actively enable that automatic connection** with an option.

```ruby
class Create < Trailblazer::Operation
  step :a
  fail :b, fast_track: :fail
  step :c, fast_track: true
  step :d
end
```
Note that the `pass_fast: true` option still works the same. This results in this diagram.

![image](https://user-images.githubusercontent.com/10406/29006361-664c35fc-7aee-11e7-8418-8c085d30be63.png)

As you can see, this simplifies the flow a lot. This is not a concern at all in TRB core since the operation really doesn't care, it's more for the users to keep it simple by specifying which step *might emit a special signal*. 

I have no experiences how widely this features is used - please comment. :beers:

**Comment by mensfeld** [comment]
I don't like the idea because if the flow is not defined explicitly in the steps API, than I have to look into the code of particular steps to understand how it can switch between tracks and what can happen.

**Comment by apotonick** [comment]
Cool, that makes two of us @mensfeld !

**Comment by mensfeld** [comment]
@apotonick  I think this could be used in the methods as long as you set up a proper flag on a step. That why I can see that there's an option that this method will be invoked in the step. To get more details I will have to see (obviously) the step definition itself but at least I will be aware (when reading the steps dsl) that case like that might occur.

I hate when someone uses something from the official API in a way that changes the flow indirectly.

**Comment by apotonick** [comment]
Yeah, I want everything to be explicit so we can infer a proper graph from it, as in the last example. :beers:

**Comment by fernandes** [comment]
explicit++

**Comment by apotonick** [comment]
In 2.1, there's now the `fast_track: true` option for the explicit connection. Otherwise, it's not connected. https://github.com/trailblazer/trailblazer-operation/blob/master/test/fast_track_test.rb#L84
