### ISSUE TITLE
Is there a nice way to exit fast on success?

### ISSUE THREAD

**Issue by ushi-as** [trailblazer/trailblazer#190]
Hi,

i have the following use case. I want to wrap severals calls to different APIs and want to exit on the first successfull call. Something like that:

```ruby
class FindSomething < Trailblazer::Operation
  step :find!

  def find!(options, params:, **)
    result = AskMyFavoriteAPI.(params)

    if result.success?
      options['findings'] = result['findings']
      return true
    end
    
    result = AskMySecondFavoriteAPI.(params)

    if result.success?
      options['findings'] = result['findings']
      return true
    end
    
    result = AskAnotherAPI.(params)
    options['findings'] = result['findings']
    result.success?
  end 
end
```

Is there a more elegant solution in trb? Something like?

```ruby
class FindSomething < Trailblazer::Operation
  step Case {
    step Nested(AskMyFavoriteAPI)
    step Nested(AskMySecondFavoriteAPI)
    step Nested(AskAnotherAPI)
  }
end
```

**Comment by apotonick** [comment]
You can use `:pass_fast`: http://trailblazer.to/gems/operation/2.0/api.html#flow-control-fail-fast-option

Or you can wait till 2.1 where you can have any wirings.

**Comment by ushi-as** [comment]
@apotonick ```:pass_fast``` is what i am looking for. Time to update the docs :) Thanks!

**Comment by apotonick** [comment]
It was an experimental feature undocumented per design! :wink: 2.1 is going to have a thorough discussion, docs, and an editor to draw and render those "circuits". Follow https://www.facebook.com/trailblazer.to if you want to stay up-to-date.

**Comment by ushi-as** [comment]
@apotonick no. i was too fast. `pass_fast:` doesnt do what i want...

```ruby 
A < Trailblazer::Operation
  step Nested(B), pass_fast: true 
  step Nested(C) 
end 

A.()
```

This code will never call the C operation. It will always exit after calling B.

**Comment by apotonick** [comment]
What should happen?

**Comment by ushi-as** [comment]
It should exit if B is successfull and execute C if B fails.

**Comment by apotonick** [comment]
Then you should use `failure` for `C`.

**Comment by ushi-as** [comment]
No. The point is to try many operations, until one is successfull.

A < Trailblazer::Operation
  step Try(B) # try b, exit on success, continue on failure  
  step Try(C) # try c, exit on success, continue on failure
  step Try(D) # try d, exit on success, continue on failure
  step Nested(E) # execute e, exit on failure, continue on success
end

**Comment by apotonick** [comment]
Ping me later on the Gitter channel, I will prepare an example how this can be done in 2.1.

Something like this? 
![image](https://user-images.githubusercontent.com/10406/30033113-962aca10-9199-11e7-8276-41c62e350ccc.png)

**Comment by ushi-as** [comment]
Exactly this.

**Comment by apotonick** [comment]
@ushi-as :point_up: I will probably make the `Merge` stuff the default (don't worry, I will document that soon), so your code would look like:

```ruby
class Create < Trailblazer::Operation
    step :a
    fail :b, connect_to: { :success => "End.success" }
    fail :c, connect_to: { :success => "End.success" }
```

Is this reasonable?

**Comment by apotonick** [comment]
Here is the final API: https://github.com/trailblazer/trailblazer-operation/blob/master/test/wiring/defaults_test.rb#L45

```ruby
 class Create < Trailblazer::Operation
    step :a
    fail :b, connect_to: Merge( success: "End.success" )
    fail :c, connect_to: Merge( success: "End.success" )
```

**Comment by apotonick** [comment]
You're now part of the official 2.1 documentation :fireworks: http://trailblazer.to/2.1/trailblazer/wiring.html#recover
