### ISSUE TITLE
Web site "Trailblazer 2.1" links to Trailblazer 2.0 release doc.

### ISSUE THREAD

**Issue by bbugh** [trailblazer/trailblazer#194]
"Wow! I'm so excited to see what is coming in 2.1!"

![image](https://user-images.githubusercontent.com/438465/32255032-fc1c679c-be72-11e7-86d1-f3ef2716dc04.png)

Where is the 2.1? This is 2.0

![image](https://user-images.githubusercontent.com/438465/32255048-1a6e467a-be73-11e7-8255-9a1feee5f645.png)

Trick or treat?! Just tricked today.

**Comment by bbugh** [comment]
You fixed it, nice.

**Comment by apotonick** [comment]
Thanks!!! I fixed it because we finally got something to say about 2.1! :stuck_out_tongue_winking_eye:
