### ISSUE TITLE
Deleting steps

### ISSUE THREAD

**Issue by milushov** [trailblazer/trailblazer#195]
Is it possible to delete steps in the inherited operation?

I found api [here](https://github.com/trailblazer/trailblazer/blob/d64500ca80a20d2414f76a5efe8a521a2124403d/test/docs/operation_test.rb#L338) but there is no information on the [docs](http://trailblazer.to/gems/operation/2.0/api.html#options-delete) (just a title)

```
  class NotPersistedMessage < Message
    step nil, delete: 'model.persist'
    step nil, delete: 'send_notifications'
    ...
  end
```

But it's not work for me:
```
TypeError: no implicit conversion from nil to integer
from /Users/roma/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:229:in `delete_at'
```

**Comment by fernandes** [comment]
hi @milushov could you please give some snippet (just the steps) for your Message class?

**Comment by milushov** [comment]
hey @fernandes, seems to be no need, because I already get that I should specify `:name` before any manipulations with steps

**Comment by fernandes** [comment]
@apotonick why reopened?

**Comment by apotonick** [comment]
To remind me, I will close it soon with a comment how to do it properly. :sparkler:

**Comment by apotonick** [comment]
Now officially documented: http://trailblazer.to/2.1/trailblazer/wiring.html#sequence-options-delete
