### ISSUE TITLE
[BUG] Rails 5.1 ^ undefined method to_prepare ActionDispatch::Reloader:Class

### ISSUE THREAD

**Issue by harunnn** [trailblazer/trailblazer#198]
ails g model Thread title:string content:text
/home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/trailblazer-rails-0.2.4/lib/trailblazer/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `to_prepare' for ActionDispatch::Reloader:Class
Did you mean?  to_param (NoMethodError)
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /home/moneytree3/Desktop/learn_trailblazer/config/environment.rb:5:in `<top (required)>'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `require'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/moneytree3/.rbenv/versions/2.3.5/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by apotonick** [comment]
Wrong gem, this should be posted here: https://github.com/trailblazer/trailblazer-rails
