### ISSUE TITLE
subclassing create operation for update

### ISSUE THREAD

**Issue by frankapimenta** [trailblazer/trailblazer#199]
the following code:

```ruby
class Ais < ApplicationRecord
  # unused class
  class Create < Trailblazer::Operation
    # ...
  end
  class Update < Create
    action :update
  end
end


```

returns the error below when starting the server:
  undefined method `action' for Ais::Update

**Comment by apotonick** [comment]
Because it's TRB 1.1, but you're using 2.0. http://trailblazer.to/gems/operation/2.0/api.html#model
