### ISSUE TITLE
Error with Wrap using ruby 2.5.0

### ISSUE THREAD

**Issue by unrooty** [trailblazer/trailblazer#204]
I updated ruby to 2.5.0 and got such error when start server: 
`syntax error, unexpected '{', expecting keyword_end (SyntaxError) ....transaction { block.call } } {`. 
I commented Wrap block and error disappered. I think it's because of changes in ruby blocks but I'm not sure.

**Comment by apotonick** [comment]
Yeah I saw that, too, it's a bug in Ruby and you should report it to bugs.ruby.org.

**Comment by adrianodennanni** [comment]
It seems that the Ruby team assumes this is not a bug: https://bugs.ruby-lang.org/issues/14433

**Comment by apotonick** [comment]
@unrooty Could you paste your `Wrap` using code snippet to bugs.ruby, so they can see how we use(d) it.

**Comment by apotonick** [comment]
The "new" syntax is documented here: http://trailblazer.to/api-docs/#operation-wrap

**Comment by nadiyaka** [comment]
@apotonick please add the parenthesis to the documentation describing Wrap:
`step Wrap(->(*, &block) { Sequel.transaction do block.call end }) {`

http://trailblazer.to/gems/operation/2.0/api.html#wrap
