### ISSUE TITLE
superclass mismatch for class <name>

### ISSUE THREAD

**Issue by geraldke** [trailblazer/trailblazer#206]
I'm getting `superclass mismatch for class` errors when using `trailblazer-loader`.

I believe the issue is because constants being loaded by `trailblazer-loader` are not getting unloaded.

Here's what I think happens:
1. `trailblazer-loader` loads a class named `User` that inherits from `ApplicationRecord`
2. When the class `User` is re-opened: `class User < ApplicationRecord`, it sees a different `ApplicationRecord` object instance (because the previous `User` wasn't unloaded) and raises the `superclass mismatch` error. I can verify this this inspecting the `object_id`s at runtime.

I know that `trailblazer` encourages explicit loading, but I wonder how it works with Rails autoloader? Pretty sure someone has already encountered this. I'm not sure if this has been raised before but I somehow can't seem to find a thread related to this on `Trailblazer`.

I've setup a basic rails app to replicate the issue:
https://github.com/geraldke/trb-loader-issue/commit/0d6c3e2eb0524438af8aba4b63b4136457951cb6

Just run a `rails console`, `reload!` and it should raise an exception.

I'm currently just using `ActiveSupport::Dependencies.explicitly_unloadable_constants` to make sure these constants are unloaded. It isn't very maintainable, but works well until I find a more elegant solution.

Btw, thank you for the awesome framework! :)

**Comment by apotonick** [comment]
Hi @geraldke, there are several problems with the loader. I switched to naming operations `Memo::Operation::Create` and the like, turned the loader off (`config.use_loader = true`) and it all works like a charm.

Let us know if that solves your problem and thanks for using this framework! :beers:

**Comment by geraldke** [comment]
Great, didn't know the loader can be disabled. I'll go with Rails auto-loading then. Cheers!
