### ISSUE TITLE
[Feature] Debugger

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer#216]
In `trailblazer-debugger`, we can use tracing that is printed when an exception is raised, showing the stack until the exception was thrown. This will improve debugging dramatically.

**Comment by LuanGB** [comment]
Hi @apotonick! I would be interested in giving a look at this. What's on your mind, and how can I get started?

**Comment by apotonick** [comment]
Hey Luan! This feature is already implemented in `trailblazer-developer` in the `Developer#wtf?` method. It works amazingly well, but we can do much more here to help developers with debugging. Would you like to help?

**Comment by LuanGB** [comment]
Certainly! Gone give a look already.

**Comment by Diego-Thomaz** [comment]
Hi @apotonick, I saw this issue is still opened. Are there any improvements to be made here? Maybe I can help.

**Comment by fernandes** [comment]
hey @Diego-Thomaz , nice to see you here! :D

upgrade to trailblazer 2.1, add `trailblazer-developer` gem, and require it on test helper

then on your test just `Trailblazer::Developer.wtf?(operation, {})`

this way you'll be able to debug the operation in an easy way

**Comment by PyrinAndrii** [comment]
Hi @apotonick, @fernandes, is the issue still actual?

I've added `gem 'trailblazer', '~> 2.1'` and was able to call `Trailblazer::Developer.wtf?(operation, {})`. But don't understand what result do you expect.
What functionality do you want to add here? Could you explain it deeper, please?

**Comment by apotonick** [comment]
Hi @PyrinAndrii here's a short video how debugging works: https://www.youtube.com/watch?v=4udzPXRh1VY

Here are docs for `Operation.wtf?` https://trailblazer.to/2.1/docs/trailblazer.html#trailblazer-developer-wtf-
Our new book also discusses `wtf?` debugging in detail, it's free! https://leanpub.com/buildalib/

```ruby
Song;:Operation::Create.wtf?(params: {...}, ...)
```

Using this approach will print the trace on the terminal.
