### ISSUE TITLE
API to deactivate cache?

### ISSUE THREAD

**Issue by saiqulhaq** [trailblazer/trailblazer#219]
Hi

I am wondering is there any way to activate cache conditionally?  
let say when developing a `Cell` in development server 

currently I do this little hack for few months, might be there is better way

```ruby
module Trailblazer

  class Cell
    class << self
      alias_method :origin_cache, :cache

      def cache(state, *args, &block)
        return unless CacheSetting.enabled?
        origin_cache(state, *args, &block)
      end
    end
  end

end
```

**Comment by apotonick** [comment]
Hi, this is the wrong repository, you want to ask here: https://github.com/trailblazer/cells-rails

**Comment by saiqulhaq** [comment]
ah sorry
