### ISSUE TITLE
cell caching is not refreshed as expected

### ISSUE THREAD

**Issue by saiqulhaq** [trailblazer/trailblazer#220]
I have a Cell class that inherit from `Trailblazer::Cell` with cache key:

```ruby
      cache :show, expiry: 1.hour do
        [model.cache_key, MyLocaleManager.normalize_locale]
      end
```

on production, the changes would not showing up unless I do Rails.cache.clear

now I am testing on development server, with Rails.perform_caching = true

I modified my Cell class to `include ::Cell::Caching::Notifications`
and create initializer file to subscribe the instrumentation

```ruby
ActiveSupport::Notifications.subscribe('write_fragment.action_controller') do |name, start, finish, id, payload|
  name    # => String, name of the event (such as 'render' from above)
  start   # => Time, when the instrumented block started execution
  finish  # => Time, when the instrumented block ended execution
  id      # => String, unique ID for this notification
  payload # => Hash, the payload
  binding.pry
end

ActiveSupport::Notifications.subscribe('read_fragment.action_controller') do |name, start, finish, id, payload|
  name    # => String, name of the event (such as 'render' from above)
  start   # => Time, when the instrumented block started execution
  finish  # => Time, when the instrumented block ended execution
  id      # => String, unique ID for this notification
  payload # => Hash, the payload
  binding.pry
end
```

and starting to make any changes, but the app still showing old template, I have tried to `touch` the `model` few times  
I have to restart server to see the new changes

FYI:
rails 4.2.10
trailblazer (2.0.7)
cells (4.1.7)
cells-rails (0.0.9)

**Comment by saiqulhaq** [comment]
FYI I don't have `:show` method on my class

so I just added `:show` method like this:


```
      def show
        binding.pry
        super
      end
```

updating model cache_key won't fire debugger

debugger is showing up if I execute `Rails.cache.clear`

**Comment by seuros** [comment]
Can you reopen this issue in cells-rails repo ?
