### ISSUE TITLE
Truly DRY Validations between ActiveRecord and TB Operations

### ISSUE THREAD

**Issue by vaskaloidis** [trailblazer/trailblazer#228]
I started implementing Operations into my app to replace my in-house ServiceBuilder. Rather than having to choose between writing validations in either a Contract or the ones I have already written in my existing ActiveRecord model, is there any good way to reference ActiveRecord validations in a TB Operation like you would a Contract?

Or has anybody written some sort of 'connector' to allow the use of AR validations from the AR Model as a contract builder? Allowing people who want to leave their validations in the Active Record Model, but so you can just  do something like `step Contract::Build( active_record: Song)`, with `Song` being a referenced regular ActiveRecord Model? 

Or even a simple 1-liner in the Contract that references an AR Model so you don't have to rewrite the validations again in that contract, or have to choose between writing the validations once either in the contract there or in the AR Model? If nobody has done this yet - should I look into writing a solution like this, or is there a good reason why nobody has done this yet, and should I not waste my time.

New to TB, but I love it thus far as I start to transition more and more feature into my apps.

**Comment by vaskaloidis** [comment]
You can remove this issue, I think I missed this link (below) when I was searching the docs earlier - I think I have found what I am looking for: http://trailblazer.to/gems/reform/rails.html#activerecord-compatibility

**Comment by konung** [comment]
Hi Vas.

Reform  ( contracts) supports AV out of the box.  You can just move them.
http://trailblazer.to/gems/reform/validation.html

Going forward dry-validations is the way to go, but as of right now - AV will work fine. In the future they will probably be moved into a separate gem .

Also - docs are in the state of flux right now. So tests ( for the gems) are probably the best place to glean off usage examples, in addition to Gitter or premium Slack channel


Have a great day!

Nick Gorbikoff
nick.gorbikoff@gmail.com

**Comment by apotonick** [comment]
Hey Vas, as you've seen, there is this "copy validations from model" feature. Unfortunately, it's not as simple as that, e.g. with custom AR validations that leverage private APIs will not function properly when copied. 

Feel free to look at it, it would be cool to have that feature work properly, but I don't think it's possible due to a lot of implications with AR's internals. Maybe we could find out what validations do _not_ work properly?
