### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by vladfaust** [trailblazer/trailblazer#229]
Hello,

The repository has two licenses, therefore I'm free to choose one upon cloning/forking. That means that if I select MIT license, I can do whatever I want with the code.

So what's the point of commerical license present here? I mean, I would get the support, but `COMM_LICENSE` file is redundant itself. Sidekiq, for example, is licensed under LGPLv3 and commerical license, so I must either abide LGPLv3 or purchase the commerical one.

I'm just pointing that out.

**Comment by apotonick** [comment]
Hi Vlad, thanks, that's very nice of you to mention that! We're putting Trailblazer on LGPLv3 very soon, hence the commercial license. Also, new website with legal FAQ coming. Thanks again! :beers: 

PS: If you can help us with answering more legal questions, please shout! :speaking_head:

**Comment by vladfaust** [comment]
Yeah, no problem, Nick. I just spent some time on digging information on OSS licensing, and narrowed to these excellent answers, they may help you as well: 

- https://opensource.stackexchange.com/questions/4693/agpl-v3-licensing-how-does-external-party-determine-if-modifications-were-made/4700#4700
- https://opensource.stackexchange.com/questions/2077/so-the-gpl-doesnt-restrict-the-creator-of-the-software-in-any-way

If you really need, you can drop me an e-mail, however, I'm not a lawyer myself 👼 

Cheers!

*closing for now*

**Comment by apotonick** [comment]
@vladfaust Hey Vlad, have you read a bit about LGPLv3? That's the license we want to apply to Trailblazer, along with a commercial license. Main goal is not money-making via licenses (that would be naive haha) but raising awareness to OSS, the work and the value behind it.

**Comment by vladfaust** [comment]
Hi Nick,

Sorry for the delay. 

Yeah, viral licenses like GPL will require to disclose the source, and it could increase the amount of OSS projects, in theory. However, GPL have a lawhole allowing to use the closed source code in SaaS products. Consider AGPL3 then.

Trailblazer is quite "intimate" product requiring integration with an application code (i.e. class extension or inheritance), so *GPL will work nicely.

And money-making is absolutely great as soon as you ask successfull businesses to share revenue with you - creator of foundation of that particular business. However, this is what *GPL lacks of - it requires commercial license as soon as the code is closed, without worrying about how much does business earn. 

It's a place for your own license then. I advise you to find a qualified lawyer to create your own license which requires to pay only if a business makes, say, $10'000+ per year. You could take existing *GPL license as a base (it should be extendable itself, not sure though about licensing of these licenses 😆).

You could also make this lawyer-ed license open-source and call it something like "Freemium Public License". I'd participate in such an activity. In fact, I'm about to create such a license but for a compiled software (I'm working on Crystal), which would be slightly different from a license for Ruby products.

Cheers,

**Comment by vladfaust** [comment]
Hello, Nick,

Have you considered my idea of Freemium license? Got any luck on that?
