### ISSUE TITLE
README link to "The Trailblazer Stack." is broken

### ISSUE THREAD

**Issue by PragTob** [trailblazer/trailblazer#231]
Points to: https://camo.githubusercontent.com/9cf0ba9ec579659c8247b94924f384b85d5b787f/68747470733a2f2f7261772e6769746875622e636f6d2f61706f746f6e69636b2f747261696c626c617a65722f6d61737465722f646f632f6f7065726174696f6e2d323031372e706e67 which can't find anything for me. :)

**Comment by roryokane** [comment]
It works for me. And the following image, with that same URL, loads:

![diagram of the Trailblazer stack](https://camo.githubusercontent.com/9cf0ba9ec579659c8247b94924f384b85d5b787f/68747470733a2f2f7261772e6769746875622e636f6d2f61706f746f6e69636b2f747261696c626c617a65722f6d61737465722f646f632f6f7065726174696f6e2d323031372e706e67)

**Comment by fernandes** [comment]
hey @PragTob maybe was some glitch on your connection... @roryokane thanks for confirmation, closing 😉

**Comment by PragTob** [comment]
Weird works for me now as well, sorry for the trouble :woman_shrugging:

**Comment by fernandes** [comment]
no worries, thanks for reporting :)
