### ISSUE TITLE
Generator Namespace / Documentation

### ISSUE THREAD

**Issue by kevinelliott** [trailblazer/trailblazer#232]
The `trailblazer-generator` from master will create operations in a sub namespace.

So while examples in documentation show:
```
  class Song::Create < Trailblazer::Operation
  end
```

the generator makes:

```
module Song::Operation
  class Create < Trailblazer::Operation
  end
end
```

This is counter-intuitive that the documentation conflicts with what the generator creates, and I imagine that means executing the operation changes to `Song::Operation::Create.()` but it is unclear which approach to take when you are learning Trailblazer.

Is this namespacing the new/*preferred* way to create concepts?

**Comment by fernandes** [comment]
hi @kevinelliott 

Yeah, it's...

the "old" way, `Song::Create`, was considering files under `app/concepts/song/operation/create`, it clashes with rails, so [trailblazer-loader](https://github.com/trailblazer/trailblazer-loader) was needed, it always load the files.

In some big projects, using spring or something like that, the loader was loading all files over and over again, in some cases delaying 2, 3s YMMV (in production as loads once, no negative impact)

So nowadays the best approach is use `Song::Operation::Create` under `app/concepts/song/operation/create` and let's rails take care of it (or load under sinatra/hanamic) following the ruby standard.

Makes sense? :)
