### ISSUE TITLE
Tried to Sign Up for Pro Support

### ISSUE THREAD

**Issue by kfitzvineti** [trailblazer/trailblazer#233]
Tried to sign up for Pro Support around 12:30pm Pacific on May 17. Email from kfitz.me domain.

The Stripe form seemed to work, but then responded with a 400 and blank page.

**Comment by apotonick** [comment]
Hi! We shut down the old PRO in favor of the new upcoming PRO. You haven't been charged or anything. Best is to follow our Facebook page where we will announce new stuff! :beer:
