### ISSUE TITLE
How to raise ActiveRecord::Rollback properly from a transaction macro

### ISSUE THREAD

**Issue by ace-subido** [trailblazer/trailblazer#234]
## Version
trailblazer 2.0.7

## Context:

I wrote an operation that saves a `Something` object. It looks like this
```
# operation class
...
step Wrap(::ActiveRecordTransactionMacro) {
  step Model(Something, :new)
  step Contract::Build(constant: Contracts::Create)
  step Contract::Validate(key: :something)
  step Contract::Persist()
  step :after_persist, fail_fast: true
}
...

# macro class
class ActiveRecordTransactionMacro

  extend Uber::Callable

  def self.call(*, &block)
    ActiveRecord::Base.transaction do
      block.call
    end
  end

end
```

I'm writing specs to test the behavior of my `after_persist`. One scenario is that it this `after_persist` fails. So I fail it using `Railway.fail_fast!`. The problem arises where my `rspec` tests says the that `op.success?` returns true instead of actually failing.

[I circle back to the documentation and it says I should return the value that decides the left or right track](http://trailblazer.to/gems/operation/2.0/api.html#wrap-callable)

I inspect what `block.call` returns and it looks like an array:

```
2.5.5 (ActiveRecordTransactionMacro):0 > block_result[0]
=> Trailblazer::Operation::Pipetree::Railway::FailFast < Pipetree::Railway::Left
```

So I changed my macro class to this:

```
class ActiveRecordTransactionMacro

  extend Uber::Callable

  def self.call(*, &block)
    ActiveRecord::Base.transaction do
      block_result = block.call
      block_result[0]
    end
  end

end
```

My test is now passing! Great! Although a part of my test dictates `model.to_not be_persisted`. So now I want to rollback my transaction if any of my steps fail. 

## Issue

Is this a good way to check for the pipetree deviating to the left?

```
class ActiveRecordTransactionMacro

  extend Uber::Callable

  def self.call(*, &block)
    ActiveRecord::Base.transaction do
      block_result = block.call
      pipe_result = block_result[0]
      pipe_result_name = pipe_result.superclass.name

      if pipe_result_name.eql? "Pipetree::Railway::Left"
        raise ActiveRecord::Rollback
      end

      pipe_result
    end
  end

end
```

Checking against `superclass.name` looks kinda funky, but it works. I don't know if there's something I haven't read in the documentation and checking out `apotonick/pipetree` seems like it's just a `Left = Class.new(Track)`. 

Regardless, I'd like to get some opinions on how to implement raising ActiveRecord rollbacks properly with Macros.

**Comment by Tab10id** [comment]
Ok. Since nobody still answered this, there our solution:
```ruby
class TransactionStep
  extend Uber::Callable

  def self.call(_ctx, *)
    ActiveRecord::Base.transaction { yield }&.first
  end
end
```
```ruby
step Wrap(TransactionStep) {
   step :one
   step :two
   step :three

   failure RollbackStep
}
```
```ruby
class RollbackStep
  extend Uber::Callable

  def self.call(*)
    raise ActiveRecord::Rollback
  end
end
```
In our solution you need to have `failure RollbackStep` in each transaction step but we think that it looks pretty straightforward and check this while code review.

**Comment by apotonick** [comment]
You don't need `Uber::Callable` anymore since somewhere in 2.0. :stuck_out_tongue_winking_eye:

**Comment by ace-subido** [comment]
Got it! Thanks for the inputs guys :D Closing this issue

**Comment by skcc321** [comment]
If I do raise ActiveRecord::Rollback, I'll lose `ctx` from the `yield`. Is there some proper way of transaction rollback without losing the inner `ctx`?

**Comment by apotonick** [comment]
@skcc321 Could you provide a quick example of your transaction code and how you'd use the "inner ctx"? :beers:

**Comment by Tab10id** [comment]
Our implementation for 2.1
```ruby
class TransactionStep
  class << self
    def call((_ctx, _flow_options), *)
      signal = ctx = flow_options = nil

      ActiveRecord::Base.transaction do
        signal, (ctx, flow_options) = yield

        raise ActiveRecord::Rollback if ctx[:_rollback!]
      end

      [signal, [ctx, flow_options]]
    end
  end
end

class RollbackStep
  class << self
    def call((ctx, flow_options), **)
      ctx[:_rollback!] = true

      [Trailblazer::Operation::Railway.fail!, [ctx, flow_options]]
    end
  end
end
```

**Comment by yogeshjain999** [comment]
@Shetty-Tejas The return value of `call` should be `signal` (Left or Right) and not `Trailblazer::Activity::End` instance.

Try below example if it works for you!

```ruby
signal = nil
ActiveRecord::Base.transaction do
  signal, (ctx, flow_options) = yield

  # define "new_signal" which is NOT an instance of `Trailblazer::Activity::End`
  new_signal = if [:success, :pass_fast].include?(signal.to_h[:semantic])
                 Railway.pass!
               else
                 Railway.fail!
               end

  raise ActiveRecord::Rollback if new_signal == Railway.fail!
end

[new_signal, [ctx, flow_options]]
```

**Comment by Shetty-Tejas** [comment]
@yogeshjain999 Thanks for the response bro 😄 . The problem that I'm facing is if you look at my example code:
```
class Model::Operations::Delete < Base::Operation
  step :a 
  step :b 
  step Wrap(WrapCallable) {
    step :c 
    step :d 
    ...
  }
  ...
end
```
Suppose the `step :c` passes but the `step :d` returns a false. Since this is a database transaction, I'd like the operation to stop there which is working fine. But, in the WrapCallable code, the signal yields a :success, irrespective of the Wrap step failing (I assume it's because at least one step, `step :c` here, passed but I'm not really sure) causing a partial database transaction. So even if I make the above changes, it's still not raising a rollback if the steps within the wrap fails.

**Comment by apotonick** [comment]
@Shetty-Tejas Could you run the setup using `wtf?` and paste the trace here? https://trailblazer.to/2.1/docs/developer.html#developer-developer-gem-wtf- Are you 100% sure that step `:d` returns false? Because by design, the `signal` in `WrapCallable` should be `:failure` in this case, as @yogeshjain999's code shows. :coffee:

**Comment by Shetty-Tejas** [comment]
@apotonick Yeah I'll paste the trace here in a while 😄 Regarding step :d returning false is I'm hundred percent sure, as I've hardcoded false as a return value for testing purposes.

![image](https://user-images.githubusercontent.com/74608924/176362676-0fdaba8f-43ed-4da3-b69b-b9b8de097aa1.png)

You can see the delete_data method returning false explicitly. Yet the result is a success.

**Comment by yogeshjain999** [comment]
@Shetty-Tejas what happens if you try the example I pasted above ?

The signal returned from `Wrap` should be either `Trailblazer::Activity::Left`, `Trailblazer::Activity::Right` or any boolean value. Anything apart from that will be considered success (even `Trailblazer::Activity::End(:failure)`).

**Comment by Shetty-Tejas** [comment]
Okay so one thing I messed up before was in the operation, the delete_data step is written as `pass :delete_data`, which I think was causing it to check whether the previous step was a success, and it returned a success in that case. Changing that pass to a step is working, and it's returning a failure now so that's on me 😛. 
However, is there a way for this to work with pass steps as well? There's a lot of places where pass steps are mentioned which will be a pain to refactor. So is there any way we can just make that work?

**Comment by apotonick** [comment]
@Shetty-Tejas The definition of `pass` steps is that they ignore the return value, so they will always pass: https://trailblazer.to/2.1/docs/activity.html#activity-strategy-railway-pass Why would you use `pass` if you want `step`, I wonder? :stuck_out_tongue_winking_eye:

**Comment by Shetty-Tejas** [comment]
@apotonick Yea man even I agree with that sentiment 😛. There's definitely some confusion regarding the pass step that which I should be raising with the team.

**Comment by Shetty-Tejas** [comment]
P.S @apotonick and @yogeshjain999 thank you guys so much for the help btw. You guys rock! 🥂

**Comment by Shetty-Tejas** [comment]
@apotonick Sorry didn't reply to this previously as I've been a little busy. Previously, when I started working with Trailblazer, I always thought of a pass step as something that will only work if the previous step is a success (much opposite to how a fail step works). I guess that's where the confusion began? Deep diving into the documentation did give me the clarity of how the pass step works. I guess that could be clearer in the documentation if that makes sense? 😄

**Comment by apotonick** [comment]
We added much nicer docs for this use-case: https://trailblazer.to/2.1/docs/macro#macro-wrap-transaction :coffee:

**Comment by MASTERSCODE735** [comment]
I have used this implementation
class TransactionStep
  def self.call(_ctx, *)
    ActiveRecord::Base.transaction { yield }&.first
  end
end

class RollbackStep
  def self.call(*)
    raise ActiveRecord::Rollback
  end
end

step Wrap(TransactionStep) {
   step :one
   step :two
   step :three
   fail RollbackStep
}

I need another fail task after rollback so I tried this
step Wrap(TransactionStep) {
   step :one
   fail RollbackStep
}
  fail :after_rollback
  
  but the rollback not working, all the changes are commited, the trace
  |-- Start.default
    `-- Wrap/id
        |-- Start.default
        |-- one
        |-- RollbackStep
        |-- next_step
        `-- End.failure
    |--after_rollback ------ I need this step after rollback is done
    |--End.failure
