### ISSUE TITLE
workflow link broken on homepage

### ISSUE THREAD

**Issue by jtmkrueger** [trailblazer/trailblazer#238]
Trying to find the docs, and the link [here](is broken). Are there active docs for this project still?

**Comment by yogeshjain999** [comment]
Hey @jtmkrueger, For which version and feature of TRB are you trying to find a doc ?

**Comment by jtmkrueger** [comment]
There's no consolidated place for me to find them? I'm working on upgrading an old application that's been AFK for a while.

**Comment by jtmkrueger** [comment]
Wow, I just re-read my issue, the place where the link is broken: https://github.com/trailblazer/trailblazer#workflows

**Comment by KamilMilewski** [comment]
@jtmkrueger the most uptodate doc for trailblazer 2.1 is here:
http://2019.trailblazer.to/2.1/docs/trailblazer.html
for 2.0:
http://trailblazer.to/guides/

**Comment by apotonick** [comment]
@jtmkrueger I guess what you're looking for are the docs for the `workflow` gem?! They are still in progress but I promise they will be published along with a nice tutorial (and the gem) within the next weeks :cough:

**Comment by jtmkrueger** [comment]
Yea I'm slogging through upgrading an app that was originally using Trailblazer 0.3.3 up to 2.1 (along with all the other rails gems that need to get bumped up as well) and any documentation links are awesome, Thanks so much @KamilMilewski!
@apotonick sounds good, my issue was just pointing out that the link in that section to documentation _(the "on our website" link)_ sends you to https://2019.trailblazer.to/docs/workflow which returns an nginx 404. Any additional docs that you put out would be awesome and welcome! I'm mostly iterating through stack traces and reading source for the suite of trailblazer gems right now to garner a grasp of the philosophy and inner workings, so docs and tutorials would be epic.

**Comment by KamilMilewski** [comment]
@apotonick since the bug with link here is fixed I think this issue can be closed

**Comment by apotonick** [comment]
@jtmkrueger I'm finishing up the last missing piece (`endpoint`) currently, and then move on to a tutorial about `workflow` :beers: ! In the meantime, the crew @yogeshjain999 and @KamilMilewski are extending the docs.
