### ISSUE TITLE
Can't reload Trailblazer Operations

### ISSUE THREAD

**Issue by nicolaep** [trailblazer/trailblazer#242]
Could you please help me with this problem?

Steps to reproduce:

```rb
module Commands
  class Foo < Trailblazer::Operation
    step :bar

    def bar
    end
  end
end

bundle exec bin/console

pry(main)> reload-code Commands::Foo
RuntimeError: ID bar! is already taken. Please specify an `:id`.
from /Users/nicolaeparaschiva/.rvm/gems/ruby-2.6.4@aid/gems/trailblazer-activity-dsl-linear-0.2.6/lib/trailblazer/activity/path.rb:88:in `raise_on_duplicate_id'
```

Dependencies:

```rb
Ruby 2.6.4
  gem 'trailblazer', '~> 2.1'
  gem 'puma', '~> 4.3', '>= 4.3.1'
  gem 'sinatra', '~> 2.0', '>= 2.0.8.1'
  gem 'dry-system', '~> 0.15.0'
```

**Comment by apotonick** [comment]
Your autoloader is confused because you're not following the conventions somewhere, see https://trailblazer.to/2.1/docs/trailblazer.html#trailblazer-rails :wink:

**Comment by nicolaep** [comment]
@apotonick but I don't use Rails.

**Comment by apotonick** [comment]
We might need @solnic's help, then. It looks as if the class instance variables bleed through even after the reload.

**Comment by seuros** [comment]
@nicolaep can you tell me the relative path of Foo operation from the root_path.

**Comment by nicolaep** [comment]
@seuros Sure.

```rb
# app/commands/foo/bar.rb
module Commands
  module Foo
    class Bar < Trailblazer::Operation
```

**Comment by seuros** [comment]
@nicolaep , the path is correct. Seem something off with the reloader of sinatra.

**Comment by apotonick** [comment]
@nicolaep Is `dry-system` doing the reloading?

**Comment by nicolaep** [comment]
@apotonick Yes, but I'm not sure if it does when I use `reload-code`. There're some ActiveSupport logic.
