### ISSUE TITLE
Ruby 3.0, is it broken?

### ISSUE THREAD

**Issue by apuntovanini** [trailblazer/trailblazer#244]
This is the error we receive on standard operation:

`Workspace::Create./usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.3.4/lib/trailblazer/activity/path.rb:127:in `append_end_options': wrong number of arguments (given 1, expected 0; required keywords: task, magnetic_to, id) (ArgumentError)`

**Comment by seuros** [comment]
It not supported fully yet.

**Comment by apuntovanini** [comment]
Thanks for quick answer! It appears is not supported at all (just created a simple operation in the concepts folder and puma fails to start). Maybe it's best to have some dependencies on ruby <3 until it's solved, what do you think? Do you need any help to support ruby 3?

**Comment by yogeshjain999** [comment]
Hey @apuntovanini, We're working on making TRB gems compatible with ruby-3. Few are almost done and few are remaining.  Any PRs are welcome 🍻

**Comment by apuntovanini** [comment]
Thanks @yogeshjain999!

**Comment by apuntovanini** [comment]
Hello @yogeshjain999, any news on this? Can you help pointing me to some specific issues you're facing so I can try to work on a PR? Thanks!

**Comment by serhii-bodnaruk** [comment]
Hey guys. Any updates regarding this issue?

**Comment by apotonick** [comment]
All gems except for Reform and Representable are already upgraded, @yogeshjain999 what's the state of Reform? :beers:

**Comment by yogeshjain999** [comment]
Just created a PR in `representable` which was a hold back to `reform`. https://github.com/trailblazer/representable/pull/247

So `reform`, `representable`, `disposable` and `declarative-builder` are working locally on ruby-3 🎉 , will create respective PRs after `representable-3.1.0` is released.

**Comment by yogeshjain999** [comment]
All dependent gems are working on ruby-2.7+ 🍻, closing this issue.
Thanks for reporting it @apuntovanini!

**Comment by apuntovanini** [comment]
Amazing work, thanks!
