### ISSUE TITLE
Request for Test: 2.1.2

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer#249]
`Gemfile` (01-Dec-22)

```ruby
gem "trailblazer-activity-dsl-linear", github: "trailblazer/trailblazer-activity-dsl-linear"
gem "trailblazer-activity", github: "trailblazer/trailblazer-activity"
gem "trailblazer-developer", github: "trailblazer/trailblazer-developer"
gem "trailblazer-macro", github: "trailblazer/trailblazer-macro"
gem "trailblazer-macro-contract", github: "trailblazer/trailblazer-macro-contract"
```

**Comment by apotonick** [comment]
New docs for `Wrap()`: https://macro-chapter--ornate-heliotrope-1c15e2.netlify.app/2.1/docs/macro#macro-wrap

**Comment by apotonick** [comment]
`Each()` macro released: https://macro-chapter--ornate-heliotrope-1c15e2.netlify.app/2.1/docs/macro#macro-each

**Comment by apotonick** [comment]
The Inject/In sorting bug is now fixed: https://github.com/trailblazer/trailblazer-activity-dsl-linear/issues/60

**Comment by Tab10id** [comment]
I don't test new features yet but all existed tests are green for us.

**Comment by apotonick** [comment]
@Tab10id :green_heart: big love from Berlin!

**Comment by n-rodriguez** [comment]
Everything is green here too :)

**Comment by apotonick** [comment]
Thanks so much @n-rodriguez :green_heart: appreciate it a lot!

**Comment by apotonick** [comment]
Many thanks for testing to all of you! https://dev.to/trailblazer/trailblazer-212-bringing-the-each-macro-1j5l
