### ISSUE TITLE
Default value in form based on controller-known values

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [trailblazer/trailblazer#48]
Hey,

I tried to add a default value to my contract basing on `controller.request` and didn't find any way to do it. Explored all the way of instantiating and creating for form object and looks like this can't be done.

Can you give me an advice?

I managed to do it in the template, but that's not what we actually want.

**Comment by fernandes** [comment]
@dmitriy-kiriyenko this can solve your problem? https://github.com/apotonick/reform#default-values-for-presentation

could you please provide more details?

**Comment by apotonick** [comment]
I think @dmitriy-kiriyenko needs a way to set a default value when `#validate`ing.

Also, the technique described in the README will be changed in Reform 2.0 as the current way of overriding the presenter method leads do unexpected results (sorry @fernandes I didn't tell you, yet :kiss: ).

You could inject the default value into the form using the constructor, or extend `#validate` and then process it in `#validate`.

```ruby
class SongForm < Reform::Form
  def initialize(model, defaults)
    super(model)
    @defaults = defaults
  end

  # or:
  def validate(params, defaults)
    # in both cases, do your default stuff here.

    super(params)
  end
end
```

In Reform 2.0, this will work as follows.

```ruby
class SongForm < Reform::Form
  property :title, default: -> (options) { options[:title] || "O.C. Confidential" }
```

Where `validate` allows you to inject options.

```
form.validate(params, title: "Creatures")
```
