### ISSUE TITLE
Consider Yardoc or other doc standard

### ISSUE THREAD

**Issue by baweaver** [trailblazer/trailblazer#75]
Fairly straightforward as the title indicates, consider adding yardoc or another standard to the code.

As an aside, I could do most of it, leaving comments on a PR where I don't quite understand the nature of a part of code.

**Comment by apotonick** [comment]
I like the idea of standardizing comments very much! I already try to document/comment relevant methods. 

However, I don't like the [style](https://github.com/lotus/validations/blob/bfe1bc9d2a8b6000bddfeb3ffd145854f5832005/lib/lotus/validations.rb) where every method has +10 lines of docs even though it's just a reader, or even a private method that might change in the next commit. 

I tend towards documenting relevant methods, only, as many other gems do it, but here we can absolutely find a standard. What's your thoughts on this? Did you mean to document everything or just semi-public/public?

**Comment by baweaver** [comment]
Mainly API, which would be public methods. There are ways to generate it for you (sublime-yardoc) to make it trivially easy.

Honestly though I find the more accurate and detailed I am in the docs, the less questions I get later about how something works. Added perk, I tend to forget what I was on about a few weeks ago and that helps clarify what in the world I was thinking.

**Comment by apotonick** [comment]
Yeah I get that, but I find it confusing and waste of space and energy to document every bloody little getter and it doesn't help me to see how this class actually does things (even though my naming is brillant, I know, thanks). TBH in the past 10 years I didn't have too many complaints about code documentation, my problem is more the conceptual documentation of how things work together.

**Comment by apotonick** [comment]
Oh, and you're mooore than welcome to help on both!!!! :fireworks:

**Comment by baweaver** [comment]
Yeah, when I get a few free minutes. Screwing around with React and decided to play with a slightly different backend.
