### ISSUE TITLE
Remove validations on inherited operations

### ISSUE THREAD

**Issue by AndrewSwerlick** [trailblazer/trailblazer#83]
I have two operations where one inherits from the other. The create operation requires data that the update operation does not, so there are a few validators defined on create that should not be on update. Is there a way to have update inherit from create and then remove the unnecessary validations, or do I need to consider an alternative inheritance/reuse strategy?

**Comment by fernandes** [comment]
hi @AndrewSwerlick ,

When it happens, I do one of the following:

1. create a [reform module](https://github.com/apotonick/reform#forms-in-modules) and use composition if make sense in real world (eg. AddressForm / TelephoneForm are composed in a ProfileForm)

2. if I just need to change a field (think its your case), I do

```ruby

class Thing
  class Create < Trailblazer::Operation
    contract do
      property :x
      property :y
    end
  end

  class Update < Create
    contract do
      property :y, readable: false # can use writeable, or virtual
    end
  end
end
```

helped you?

**Comment by apotonick** [comment]
@fernandes Good idea with the _form module_.

@AndrewSwerlick As Celso says, you have to use `Reform::Form::Module`. This is documented [here](https://github.com/apotonick/reform#forms-in-modules( (not in the book, so far, and not sure if I should mention it).

In the module, you can have shared logic and then include it in both contracts.

In Reform 2.1 (or 2.2, not sure if I will manage to push that into the upcoming 2.1), you can have validation groups: https://github.com/apotonick/reform/wiki/Rich-Validations They will be removeable when inheriting.

Let me know if you need more help here! :beers:

**Comment by AndrewSwerlick** [comment]
No that's clear. I suspected modules were going to be the approach, and that's what I meant by alternative inheritance/reuse strategy. I just wanted to make sure.

**Comment by fernandes** [comment]
:+1: :smile_cat:
