### ISSUE TITLE
Operation contract validation idiom assumes presence of key in params hash

### ISSUE THREAD

**Issue by johnlane** [trailblazer/trailblazer#85]
The typical validation performed by an operation goes like this (see book, page 20):

``` ruby
def process(params)
  validate(params[:comment]) do
  ...
  end
end
```

This assumes that the `params` passed into the operation contains a `:comment` key and, if there isn't one, this code will fail with an error:

```
`undefined method 'has_key?' for nil:NilClass`
```

It would better to pass `params` to `validate` and let the validation extract the components it needs.

**Comment by johnlane** [comment]
A work-around to this issue is as follows:
```ruby
def process(params)
  params[:comment] && validate(params[:comment]) do
  ...
  end
  invalid!
end
```

**Comment by johnlane** [comment]
Another workaround that I tried was to pass in `params` and then nest the conract like this:
```ruby
contract do
  collection :comment do
  ...
  end
end
```
However this approach did not work when I tried with a non-model contract.

**Comment by monkbroc** [comment]
+1 I ran into this as well. I made a pull request to raise an exception in this case.

**Comment by apotonick** [comment]
I am starting to wonder if we could handle that using ruby keyword arguments. I do that in my current project and love it.

```ruby
def params(comment:) # requires comment: to be present.
  validate(comment) do

  end
end
```

**Comment by monkbroc** [comment]
Did you mean `def process(comment:)`?

**Comment by nil0bject** [comment]
yes he did
```
def process(comment:, **params) # requires `comment` to be present.
  validate(comment) do

  end
end
```

**Comment by apotonick** [comment]
Sorry, fixed!

**Comment by apotonick** [comment]
Fixed in TRB2. trailblazer.to/gems/operation/2.0/contract.html#extracting-params
